#!/usr/bin/env bash
unset AWS_ACCESS_KEY_ID
unset AWS_SECRET_ACCESS_KEY
unset AWS_SESSION_TOKEN
unset AWS_EXPIRATION		
#unset AWS_DEFAULT_REGION=us-west-2  #LEFT SET TO BE HELPFULL
export AWS_ACCESS_KEY_ID=${ORIGINAL_AWS_ACCESS_KEY_ID}
export AWS_SECRET_ACCESS_KEY=${ORIGINAL_AWS_SECRET_ACCESS_KEY}	
export PKR_VAR_access_key=${AWS_ACCESS_KEY_ID}
export PKR_VAR_secret_key=${AWS_SECRET_ACCESS_KEY}

unset ORIGINAL_AWS_ACCESS_KEY_ID
unset ORIGINAL_AWS_SECRET_ACCESS_KEY

